### ISSUE TITLE
Fails on subsequent calls to wdired-change-to-wdired-mode

### ISSUE THREAD

**Issue by bezirg** [amno1/dired-auto-readme#8]
The first switch in and out of wdired works as expected (hiding the readme).
Subsequent switching in works, but when switching out of wdired fails on the same buffer with:

dired-auto-readme--insert: Opening input file: No such file or directory, /home/path/to/Literal first line of text in README file/README.md

Sequence of steps:

```
M-x wdired-change-to-wdired-mode ; ok
M-x wdired-abort-changes ; ok
M-x wdired-change-to-wdired-mode ; ok
M-x wdired-abort-changes ; error
...
```

**Comment by amno1** [comment]
Thanks for reporting of all three issues! I have fixed this one too, but I'll have to fix my computer, seems like I can't use ssh/gpg on this one at all. In the meanwhile the fix is here:

```
(defun dired-auto-readme--find-file ()
  "Return first file-name in a `current-buffer' matching "
  (catch 'file
    (save-excursion
      (goto-char (point-min))
      (while (dired-next-line 1)
        (let ((file (file-name-nondirectory (dired-file-name-at-point)))
              (case-fold-search t))
          (when (and (file-exists-p file) (not (file-directory-p file)))
            (dolist (rg dired-auto-readme-files)
              (when (looking-at-p rg)
                (throw 'file file)))))))))
```

**Comment by amno1** [comment]
Pushed fix.
