### ISSUE TITLE
dired-create-directory wrongly jumps point to (point-min)

### ISSUE THREAD

**Issue by bezirg** [amno1/dired-auto-readme#9]
Normally after calling `dired-create-directory`, the pointer should remain where it is.

However, the advice ‘dired-auto-readme--insert’ makes the pointer jump to point-min.

The fix would be to have `dired-auto-readme--insert` retain the pointer's position

**Comment by amno1** [comment]
I see. It was a save-excursion in a wrong place, It was a trivial fix for that one, however, I have a new Windows laptop and I can't get ssh to work here so I am not able to push the fix. Here is an updated 'insert': 
```
(defun dired-auto-readme--insert (&optional _)
  "Insert content of Readme file in a current Dired buffer.

This function assumes the content is not currently inserted."
  (save-excursion
    (when-let* ((file (dired-auto-readme--find-file)))
      (with-silent-modifications
        (setq-local font-lock-fontify-region-function
                    #'dired-auto-readme--fontify-region)
        (let* ((enable-local-variables nil)
               (data (dired-auto-readme--read-in file))
               (action (assoc (cdr data) dired-auto-readme-alist)))
          (goto-char (point-max))
          (insert (car data))
          (when action
            (funcall (cdr action))))))))
```

I'll push the fix when I fix ssh  and gpg installation on this computer.

**Comment by amno1** [comment]
Should be fixed now!
